### ISSUE TITLE
[ISSUE] List of naming problems in RGI6

### ISSUE THREAD

**Issue by fmaussion** [GLIMS-RGI/rgi_issue_tracker#19]
**RGI version**
RGI v6

Submitted by @ezwelty:

- Nordlicher Schneeferner, Austria (RGI60-11.03246, no GLIMS equivalent) is positioned east of the actual glacier. The OpenStreetMap polygon (likely from an official government source), in contrast, is in close agreement with satellite imagery.
- Figure 1 and Table 1 (No. 3) in Nikitin et al. 2000 (http://www.webgeo.ru/books/MGI/88.pdf, page 145), Figure 2 in Surazakov et al. 2007 (https://doi.org/10.1088/1748-9326/2/4/045017), Figure 1 in Narozhniy & Zemtsov 2011 (https://doi.org/10.1007/s13280-011-0166-0) suggest that RGI incorrectly names RGI60-10.01708 "Vodopadniy Glacier" when it should be "Kar Malogo Aktru Glacier".
- RGI60-07.00230 is named "Finsterwalderbreen" but should be named "Leinbreen" (according to https://data.npolar.no/placename/dd5a7ecd-50d0-5447-84e7-3b12f376867e).
- RGI incorrectly names glaciers on "Rainer Island" (Franz Josef Land, Russia) as "Rainier Island".
- RGI incorrectly names glaciers on "Wilczek Land" (Franz Josef Land, Russia) as "Hall Island'.
- According to Figure 2 in Satylkanov 2018 (https://doi.org/10.3233/JCC-180009), RGI60-13.06359 is incorrectly named "Karabatkak Glacier", which is actually RGI60-13.06361.
- RGI60-01.16316 spans a divide. According to Figure 1 in Clarke & Collins 1984 (https://doi.org/10.1139/e84-032), the east-facing half is known as "Hazard Glacier".
- RGI60-10.01730 spans a divide, joining two isolated (and separately-studied) glaciers.
- Blauschnee, Switzerland (47.25037, 9.34300) and the other ice masses on Säntis not included in RGI, but included in GLIMS.
- Schwarzmilzferner, Austria (47.29796482, 10.29691371) not included in either RGI or GLIMS.
- Glacier de Tsarmine, Switzerland (46.04691948, 7.52034926) not in RGI, but included in GLIMS.
- Figure 1 in Zhang et al. 2014 (https://doi.org/10.1016/j.quaint.2013.08.035) suggests RGI60-13.45344 should be named "CN5Y730C0026", not "CN5Y730C0025".
- Figure 1 in Zhang et al. 2014 (https://doi.org/10.1016/j.quaint.2013.08.035), Figure 5.1 in Chen 2014 (https://doi.org/10.1007/978-94-017-8017-9) suggest RGI60-13.45336 should be named "CN5Y730C0030", not "CN5Y730C0031".

**Comment by ezwelty** [comment]
I think this is a duplicate of https://github.com/GLIMS-RGI/rgi_issue_tracker/issues/7.

**Comment by fmaussion** [comment]
Ha! That's embarrassing ;-) 

It's likely that the names will disappear from RGI7 though, something to discuss with the Working Group when ready.

**Comment by ezwelty** [comment]
@fmaussion For what it is worth, mapping names to geography has proven to be important for data archeology, literature reviews, and the like. Humans continue to use names to refer to glaciers, whether computers like it or not. I end up making heavy use of OpenStreetMap, Google Maps, and national maps (e.g. https://toposvalbard.npolar.no, https://map.geo.admin.ch) to figure out the geographic meaning of a name. Although names maybe shouldn't be a fundamental component of RGI, the wider community should consider maintaining a multilingual, geographic database of glacier names. That or we just link to existing online resources...

**Comment by fmaussion** [comment]
@ezwelty thanks a lot for your input. I agree! 

I should have explained better: it is not part of RGI7v1 to transfer the names of RGI6 to RGI7 (because of the big change in production workflow). However, the outlines will carry over the names from the GLIMS attribute table, i.e. this is where we will have to store them in the future (and, possibly, update the existing database).
