### ISSUE TITLE
Can't find zmin_m, zmax_m, zmed_m, zmean_m fields in the shapefiles

### ISSUE THREAD

**Issue by petermingjing** [GLIMS-RGI/rgi_issue_tracker#45]
**RGI version**
RGI v7.0

**Describe the issue**
Just can't find zmin_m, zmax_m, zmed_m, zmean_m fields in the shapefiles. It may not be an issue but just that I can't find them.

**Expected outcome**
Maybe add an instruction line here, https://www.glims.org/rgi_user_guide/products/glacier_product.html.

**Screenshots**

**Suggested solution**
Any idea you might have to solve the issue

**Additional context**

**Comment by fmaussion** [comment]
Are you sure you downloaded the glacier product files (letter G) and not the glacier complex files (letter C)?

Glacier complexes don't have hypometry data yet, they will in 7.1.

**Comment by petermingjing** [comment]
You are right. I only checked the C files.
Jing

On 29 Oct 2023, at 10:36, Fabien Maussion ***@***.***> wrote:



Are you sure you downloaded the glacier product files (letter G) and not the glacier complex files (letter C)?

Glacier complexes don't have hypometry data yet, they will in 7.1.
