### ISSUE TITLE
[ISSUE] misaligned RGI outlines RGI-19 

### ISSUE THREAD

**Issue by matthiasdusch** [GLIMS-RGI/rgi_issue_tracker#6]
**RGI version**
RGI v6

**Describe the issue**
I noticed some outline misalignments in RGI-19 Antarctica. For example all Laurie Island glaciers (approx. 60.73S, 44.60W).
But also around 74S, 104W (e.g. RGI60-19.01405, RGI60-19.01402, ...)

**Expected outcome**
Should align with topography

**Screenshots**
![laurie](https://user-images.githubusercontent.com/37663627/80378704-583f2e00-889d-11ea-9fb2-721c4b4cd9b3.png)

**Suggested solution**
Maybe a projection issue of the original source?

**Additional context**
@bruceraup

**Comment by bruceraup** [comment]
These outlines were first in RGI then in GLIMS; I think the original source was the ADD.  Could be a projection problem, yes.

**Comment by fmaussion** [comment]
Duplicate of https://github.com/GLIMS-RGI/rgi_issue_tracker/issues/14
